export const CARD_DATA = [
  'Dating',
  'I am pregnant',
  'Are you two together?',
  'Can you come over',
  'I love you',
  'Meet my mom',
  'How do I look?',
  'You look beautiful',
  'Meet my boyfriend',
  'Vacation',
  'Dinner date',
  'Grab a coffee',
  'Can you talk?',
  "We can't do this",
  'My sweetheart',
  'Love of my life',
  'Will you marry me?',
  'I hate you',
  'I want to see you',
  'Meet my girlfriend',
  'Gorgeous',
  '(Sex scene)',
  'I will call you',
  'Leave my house',
  'We are just friends',
];
